### ISSUE TITLE
Searching IDs with .find(), search in whole document

### ISSUE THREAD

**Issue by Sw0rdiX** [Veams/query#5]
https://github.com/Veams/query/blob/ec001ae352a7bb01fe51585a7a576f754b7c6b54/src/index.ts#L82

Hi, 

in case of use the find() function of an VeamsqueryObject to search an ID in the context, the result gets wrong (as i expected). I expected that the ID will only search in the context, but the find function call the normal Constructor that search IDs in the whole document. 

Should it be scope[i].querySelector(selector) instead of document.getElementById(selector.substr(1)) ?

**Comment by Sebastian-Fitzner** [comment]
Funny, because in general it should be only considered performance wise... 
Searching in context vs query by id is something we should compare. 

Other than that it doesn’t matter, right?! If it matters you did something wrong in your code base, because there can only be one unique id on the site.

**Comment by Sw0rdiX** [comment]
Yeah, but its just in case u want search unique ids in context of elements. And the definition of find said "descendants".  :) I already change the search style in the code, but its a logical thing against the description.

**Comment by Sebastian-Fitzner** [comment]
But how can the result be different?

**Comment by andy-gutsche** [comment]
I will fix this... :)
