### ISSUE TITLE
html() accepts string only

### ISSUE THREAD

**Issue by Sebastian-Fitzner** [Veams/query#6]
The `html()` method accepts a string only. But it would be better when it also accepts a DOM element as well. For now you have to use `outerHTML` which looks not so nice: 

### Current Implementation

``` js
const $clone = this.$el.clone(true);

this.$otherSelector.html($clone[0].outerHTML)
```

### Improvement

``` js
const $clone = this.$el.clone(true);

this.$otherSelector.html($clone[0])
```

**Comment by andy-gutsche** [comment]
v2.3.0 adds support for VeamsQuery object and DOM node as parameter
